services:
  portfolio:
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    container_name: portfolio
    environment:
      - SECRET
      - DEBUG
      - COMMENTS
      - CF_TURNSTILE_SECRET
      - CF_TURNSTILE_SITE_KEY
      - RATE_LIMIT
      - DATA_VERSION=0
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "~/.portfolio:/var/lib/portfolio"
    restart: unless-stopped