version: '3'

services:
  portfolio:
    container_name: portfolio
    environment:
      - SECRET
      - DEBUG
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "~/.portfolio:/var/lib/portfolio"
    restart: unless-stopped