from src.mdextensions.anchor_target_extension import AnchorTargetExtension
from src.mdextensions.header_anchor_extension import HeaderAnchorExtension
from src.mdextensions.image_processing_extension import ImageProcessorExtension
from src.mdextensions.slideshow_extension import SlideshowExtension
from src.mdextensions.inline_extensions import ColourExtension